import type { Metadata } from "next";
import Footer from "@/components/custom/footer";
import { Geist } from "next/font/google"

export const geist = Geist({
  weight: "400",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Book it",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es">
      <body className={geist.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
