import type { Metadata } from "next";
import Footer from "@/components/custom/footer";

export const metadata: Metadata = {
  title: "Book it",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
